[package]
name = "libaflgo"
version = "0.1.0"
authors = ["Elia Geretto <e.geretto@vu.nl"]
edition = "2021"

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
libafl = { git = "https://github.com/AFLplusplus/LibAFL.git" }
libaflgo_targets = { path = "../libaflgo_targets" }
