[package]
name = "libaflgo"
version = "0.1.0"
authors = ["Elia Geretto <e.geretto@vu.nl"]
edition = "2021"

[dependencies]
libafl = { workspace = true }
serde = { version = "1.0.160", features = ["derive"] }
