[package]
name = "libaflgo_targets"
version = "0.1.0"
authors = ["Elia Geretto <e.geretto@vu.nl"]
edition = "2021"

[dependencies]
libaflgo = { path = "../libaflgo" }
libafl = { workspace = true }
serde = { version = "1.0.160", features = ["derive"] }